### PR TITLE
added esp32-awsiot article, closes #6

### LINKED ISSUE #6: Blog on ESP32 AWS IoT certs in SPIFFS

### PR DESCRIPTION
**Pull request by KaranRajPradhan**

### CODE REVIEW

**Comment by hairyhoncho** [comment]
Edited the documentation. Clear, concise article. Good work Karan.

**Review by hairyhoncho — APPROVED** [review]

**Comment by tejpochiraju** [comment]
I realised after merging and have fixed it but images should go in the `images/` directory in root. The way markdown is rendered for you locally is not how Jekyll locates the files. 

@KaranRajPradhan @hairyhoncho

**Comment by tejpochiraju** [comment]
Sorry, guys. I disagree with the assessment - there's too much fluff. Editing. Also, the article is supposed to focus on one specific point - using SPIFFS to store certificates but that messaging is lost.

**Comment by tejpochiraju** [comment]
A few pointers:

- Titles should be specific and use key words that lead to searchability. 
- Use `AWS IoT` not `AWS IoT Core`, we don't need to be that specific.
- Use fewer words where needed, e.g. "is a tool that automates..." -> "automates..."
- Put a blank line after headers and before lists for improved readability while editing (has no effect on generated HTML)
- Link to `register.py` was broken.
- No colons in headings
- `prepare.sh` does not need and should not be run with `sudo`.
- The image was not vertically centered and had too much background.

Edited and deployed: https://iotready.co/blog/esp32-aws-iot-shadow-with-spiffs/

**Pull request merged**
